- name: Create app directory
  file:
    path: /opt/flask-app
    state: directory
    mode: '0755'

- name: Copy Flask app
  copy:
    src: app.py
    dest: /opt/flask-app/app.py
    mode: '0755'

- name: Copy init_db.sql
  copy:
    src: init_db.sql
    dest: /opt/flask-app/init_db.sql
    mode: '0644'

- name: Initialize SQLite database
  ansible.builtin.shell: sqlite3 "{{ app_dir }}/data.db" < "{{ app_dir }}/init_db.sql"
  args:
    creates: "{{ app_dir }}/data.db"


- name: Copy templates
  ansible.builtin.copy:
    src: templates/
    dest: "{{ app_dir }}/templates/"
    mode: '0755'

- name: Create systemd service for Flask app
  copy:
    dest: /etc/systemd/system/flask-app.service
    content: |
      [Unit]
      Description=Flask App
      After=network.target

      [Service]
      User=ec2-user
      WorkingDirectory=/opt/flask-app
      ExecStart=/usr/bin/python3 app.py
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start Flask app
  ansible.builtin.systemd:
    name: flask-app
    state: started
    enabled: yes
