- name: Download artifact from S3
  amazon.aws.s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ artifact_name }}"
    dest: "/tmp/{{ artifact_name }}"
    mode: get
    region: us-east-1
  vars:
    ansible_python_interpreter: "{{ venv_dir }}/bin/python3"

- name: Clean old current symlink or directory
  file:
    path: "{{ app_dir }}/current"
    state: absent

- name: Ensure releases parent directory exists
  file:
    path: "{{ app_dir }}/releases"
    state: directory
    owner: "{{ flask_user }}"
    group: "{{ flask_user }}"
    mode: '0755'

- name: Ensure current release directory exists
  file:
    path: "{{ app_dir }}/releases/{{ build_id }}"
    state: directory
    owner: "{{ flask_user }}"
    group: "{{ flask_user }}"
    mode: '0755'

- name: Extract artifact into release directory
  unarchive:
    src: "/tmp/{{ artifact_name }}"
    dest: "{{ app_dir }}/releases/{{ build_id }}"
    remote_src: yes
    owner: "{{ flask_user }}"
    group: "{{ flask_user }}"
    mode: '0755'
    extra_opts:
      - --strip-components=1

- name: Update current symlink to latest release
  file:
    src: "{{ app_dir }}/releases/{{ build_id }}"
    dest: "{{ app_dir }}/current"
    state: link

- name: Create virtualenv if missing
  ansible.builtin.command:
    cmd: python3 -m venv "{{ venv_dir }}"
  args:
    creates: "{{ venv_dir }}"

- name: Install Python dependencies in virtualenv
  ansible.builtin.pip:
    requirements: "{{ app_dir }}/current/files/requirements.txt"
    virtualenv: "{{ venv_dir }}"
    virtualenv_python: python3

- name: Restart Flask app service
  ansible.builtin.systemd:
    name: flaskapp
    state: restarted
    enabled: yes
    daemon_reload: yes