- name: Download SonarQube
  get_url:
    url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.3.0.61060.zip"
    dest: /tmp/sonarqube.zip

- name: Extract SonarQube
  unarchive:
    src: /tmp/sonarqube.zip
    dest: /opt
    remote_src: yes

- name: Create SonarQube user and group
  user:
    name: sonar
    group: sonar
    create_home: no
    shell: /bin/false

- name: Set ownership of SonarQube folder
  file:
    path: /opt/sonarqube-10.3.0.61060
    owner: sonar
    group: sonar
    recurse: yes

- name: Set permissions of SonarQube folder
  file:
    path: /opt/sonarqube-10.3.0.61060
    mode: '0755'
    recurse: yes
