- name: Ensure wget is installed
  yum:
    name: 
      - wget
      - unzip
    state: present

- name: Create SonarQube group
  group:
    name: "{{ sonar_group }}"
    state: present

- name: Create SonarQube user
  user:
    name: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    create_home: no
    shell: /bin/bash
    state: present

- name: Create installation directory
  file:
    path: "{{ sonar_install_dir }}"
    state: directory
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    mode: '0755'

- name: Download SonarQube
  ansible.builtin.get_url:
    url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.4.0.65466.zip"
    dest: /tmp/sonarqube.zip
    headers:
      User-Agent: "Mozilla/5.0"


- name: Extract SonarQube
  unarchive:
    src: /tmp/sonarqube.zip
    dest: "{{ sonar_install_dir }}"
    remote_src: yes
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    mode: '0755'

- name: Ensure SonarQube port is open (optional)
  firewalld:
    port: "{{ sonar_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes

- name: Start SonarQube
  shell: "{{ sonar_install_dir }}/sonarqube-{{ sonar_version }}/bin/linux-x86-64/sonar.sh start"
  become: yes
  become_user: "{{ sonar_user }}"
